### ISSUE TITLE
[TODO] Transform all unsafe dict items copying

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cherrypy#1805]
Inspired by https://github.com/cherrypy/cherrypy/pull/1804, I've found a few places which look like `list(some_dict.items())` which is supposed to create a copy of data. The problem is that in Python 3 `dict.items()` is a generator and, when race conditions occur, it raises `RuntimeError: dictionary changed size during iteration`.

It looks like, if we transform all of the places to `list(some_dict.copy().items())`, the problem should be solved.
Ref: https://blog.labix.org/2008/06/27/watch-out-for-listdictkeys-in-python-3

**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**

bug (kinda/potentially)

**What is the current behavior?**

it's risky because this can crash threads

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

* [x] https://github.com/cherrypy/cherrypy/blob/e5de08887ddb960b337e1f335c819c0b2873d850/cherrypy/lib/caching.py#L199
* [x] https://github.com/cherrypy/cherrypy/blob/5f8d4358cfc7580bdb22e471dd1e4b03cc3887c5/cherrypy/lib/cpstats.py#L208
* [x] https://github.com/cherrypy/cherrypy/blob/87375aa11c995fc5ab237755ee4c75354540aef8/cherrypy/test/test_logging.py#L42
* [x] https://github.com/cherrypy/cherrypy/blob/2fc78dc9af3e556829ce69d3e1311e5629200882/cherrypy/test/test_config.py#L83
* [ ] https://github.com/cherrypy/cherrypy/blob/2fc78dc9af3e556829ce69d3e1311e5629200882/cherrypy/test/sessiondemo.py#L124
* [x] https://github.com/cherrypy/cherrypy/blob/8bc3e5289c8e7b4236f93a3e387184170ede33cc/cherrypy/test/helper.py#L96
* [ ] https://github.com/cherrypy/cherrypy/blob/2fc78dc9af3e556829ce69d3e1311e5629200882/cherrypy/test/test_tools.py#L52
* [x] https://github.com/cherrypy/cherrypy/blob/2fc78dc9af3e556829ce69d3e1311e5629200882/cherrypy/_cpmodpy.py#L198
* [x] https://github.com/cherrypy/cherrypy/blob/db0a8a685cf7c9650428c0fca407e17c3a3b8fde/cherrypy/lib/sessions.py#L407

**What is the expected behavior?**

no exception

**What is the motivation / use case for changing the behavior?**

do better

**Please tell us about your environment:**

- Cheroot version: N/A
- CherryPy version: master
- Python version: N/A
- OS: N/A
- Browser: N/A

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

N/A

**Comment by eshellman** [comment]
Ah, so the behavior changed in Py3. That explains why we never saw the problem before we moved to Py3! Thanks for this improvement!

**Comment by webknjaz** [comment]
Yep :)
